/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponseDto {
  id?: string;
  isReceiverOnline?: boolean;
  lastMessage?: string;
  lastMessageTime?: string;
  name?: string;
  receiverId?: string;
  senderId?: string;
  unreadCount?: number;
}
