/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChatResponseDto } from '../models/chat-response-dto';
import { createChat } from '../fn/chats/create-chat';
import { CreateChat$Params } from '../fn/chats/create-chat';
import { getChatsByReceiverId } from '../fn/chats/get-chats-by-receiver-id';
import { GetChatsByReceiverId$Params } from '../fn/chats/get-chats-by-receiver-id';
import { StringResponseDto } from '../models/string-response-dto';


/**
 * Endpoints for managing chats
 */
@Injectable({ providedIn: 'root' })
export class ChatsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getChatsByReceiverId()` */
  static readonly GetChatsByReceiverIdPath = '/api/v1/chats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChatsByReceiverId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByReceiverId$Response(params?: GetChatsByReceiverId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatResponseDto>>> {
    return getChatsByReceiverId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChatsByReceiverId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByReceiverId(params?: GetChatsByReceiverId$Params, context?: HttpContext): Observable<Array<ChatResponseDto>> {
    return this.getChatsByReceiverId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ChatResponseDto>>): Array<ChatResponseDto> => r.body)
    );
  }

  /** Path part for operation `createChat()` */
  static readonly CreateChatPath = '/api/v1/chats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChat$Response(params: CreateChat$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponseDto>> {
    return createChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChat(params: CreateChat$Params, context?: HttpContext): Observable<StringResponseDto> {
    return this.createChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringResponseDto>): StringResponseDto => r.body)
    );
  }

}
