/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getChatMessages } from '../fn/messages/get-chat-messages';
import { GetChatMessages$Params } from '../fn/messages/get-chat-messages';
import { MessageResponseDto } from '../models/message-response-dto';
import { saveMessage$FormData } from '../fn/messages/save-message-form-data';
import { SaveMessage$FormData$Params } from '../fn/messages/save-message-form-data';
import { saveMessage$Json } from '../fn/messages/save-message-json';
import { SaveMessage$Json$Params } from '../fn/messages/save-message-json';
import { setMessagesToSeenByChat } from '../fn/messages/set-messages-to-seen-by-chat';
import { SetMessagesToSeenByChat$Params } from '../fn/messages/set-messages-to-seen-by-chat';


/**
 * Endpoints for managing messages
 */
@Injectable({ providedIn: 'root' })
export class MessagesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveMessage()` */
  static readonly SaveMessagePath = '/api/v1/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveMessage$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveMessage$Json$Response(params: SaveMessage$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return saveMessage$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveMessage$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveMessage$Json(params: SaveMessage$Json$Params, context?: HttpContext): Observable<void> {
    return this.saveMessage$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveMessage$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  saveMessage$FormData$Response(params: SaveMessage$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return saveMessage$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveMessage$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  saveMessage$FormData(params: SaveMessage$FormData$Params, context?: HttpContext): Observable<void> {
    return this.saveMessage$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setMessagesToSeenByChat()` */
  static readonly SetMessagesToSeenByChatPath = '/api/v1/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setMessagesToSeenByChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  setMessagesToSeenByChat$Response(params: SetMessagesToSeenByChat$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return setMessagesToSeenByChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setMessagesToSeenByChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setMessagesToSeenByChat(params: SetMessagesToSeenByChat$Params, context?: HttpContext): Observable<void> {
    return this.setMessagesToSeenByChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getChatMessages()` */
  static readonly GetChatMessagesPath = '/api/v1/messages/chat/{chatId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChatMessages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatMessages$Response(params: GetChatMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MessageResponseDto>>> {
    return getChatMessages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChatMessages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatMessages(params: GetChatMessages$Params, context?: HttpContext): Observable<Array<MessageResponseDto>> {
    return this.getChatMessages$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MessageResponseDto>>): Array<MessageResponseDto> => r.body)
    );
  }

}
