/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllUsersExceptSelf } from '../fn/users/get-all-users-except-self';
import { GetAllUsersExceptSelf$Params } from '../fn/users/get-all-users-except-self';
import { UserResponseDto } from '../models/user-response-dto';


/**
 * Endpoints for managing users
 */
@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllUsersExceptSelf()` */
  static readonly GetAllUsersExceptSelfPath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUsersExceptSelf()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsersExceptSelf$Response(params?: GetAllUsersExceptSelf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponseDto>>> {
    return getAllUsersExceptSelf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUsersExceptSelf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsersExceptSelf(params?: GetAllUsersExceptSelf$Params, context?: HttpContext): Observable<Array<UserResponseDto>> {
    return this.getAllUsersExceptSelf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserResponseDto>>): Array<UserResponseDto> => r.body)
    );
  }

}
